apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game-image
        image: 940622738555.dkr.ecr.eu-west-2.amazonaws.com/eks-v3:latest
        ports:
        - containerPort: 80
