apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game-image
        image: 940622738555.dkr.ecr.eu-west-2.amazonaws.com/eks-v3:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
      app: game
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: eks.ayubs.uk
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - eks.ayubs.uk
    secretName: secret-storage-key-for-tls-cert
  rules:
  - host: eks.ayubs.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-service
            port:
              number: 80

